AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  UserServiceFunction:
    Type: 'AWS::Serverless::Function'
    Metadata:
      BuildMethod: go1.x
    Properties:
      PackageType: Zip
      CodeUri: cmd/lambda
      Runtime: provided.al2023
      MemorySize: 128
      Timeout: 30
